name: Test and Submit

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  Run-React-Forms-Test:
    if: "contains(github.event.head_commit.message, 'Forms v10')"
    name: React Forms Test
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Yarn install JS project dependencies
        run: yarn install --prefer-offline --network-timeout 600000

      - name: Yarn Build
        run: yarn build
        continue-on-error: true

      - name: Copy Tests
        run: yarn copy-test

      - name: Run/Compile Tests
        run: yarn compile-test-form
        continue-on-error: true

      - name: Submit test
        run: yarn submit-test ${{ github.event.pusher.name }}

  Run-React-Mapping-Test:
    if: "contains(github.event.head_commit.message, 'Mapping v12')"
    name: React Mapping Test
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Yarn install JS project dependencies
        run: yarn install --prefer-offline --network-timeout 600000

      - name: Yarn Build
        run: yarn build
        continue-on-error: true

      - name: Copy Tests
        run: yarn copy-test

      - name: Compile Tests
        run: yarn compile-test-mapping
        continue-on-error: true

      - name: Submit test
        run: yarn submit-test ${{ github.event.pusher.name }}

  Run-React-Forms-Makeup-Test:
    if: "contains(github.event.head_commit.message, 'Forms v7')"
    name: React Forms Makeup Test
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Yarn install JS project dependencies
        run: yarn install --prefer-offline --network-timeout 600000

      - name: Yarn Build
        run: yarn build
        continue-on-error: true

      - name: Copy Tests
        run: yarn copy-test

      - name: Compile Tests
        run: yarn compile-test-form-makeup
        continue-on-error: true

      - name: Submit test
        run: yarn submit-test ${{ github.event.pusher.name }}

  Run-React-Mapping-Makeup-Test:
    if: "contains(github.event.head_commit.message, 'Mapping v11.2')"
    name: React Mapping Makeup Test
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Yarn install JS project dependencies
        run: yarn install --prefer-offline --network-timeout 600000

      - name: Yarn Build
        run: yarn build
        continue-on-error: true

      - name: Copy Tests
        run: yarn copy-test

      - name: Compile Tests
        run: yarn compile-test-mapping-makeup
        continue-on-error: true

      - name: Submit test
        run: yarn submit-test ${{ github.event.pusher.name }}

  Run-React-Practice-Test:
    if: "contains(github.event.head_commit.message, 'Practice v2')"
    name: React Practice Test
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Yarn install JS project dependencies
        run: yarn install --prefer-offline --network-timeout 600000

      - name: Yarn Build
        run: yarn build
        continue-on-error: true

      - name: Copy Tests
        run: yarn copy-test

      - name: Compile Tests
        run: yarn compile-test-practice-assessment
        continue-on-error: true

      - name: Submit test
        run: yarn submit-test ${{ github.event.pusher.name }}

  Run-Build:
    name: React Compile Test
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        continue-on-error: false

      - name: Yarn install JS project dependencies
        run: yarn install --prefer-offline --network-timeout 600000

      - name: Yarn Build
        run: yarn build
        continue-on-error: true

      - name: Copy Tests
        run: yarn copy-test
